# app-dev.yml - 开发环境特定配置
database:
  password: "123456"
  dbname: movie

jellyfin:
  api_url: "http://192.168.1.9:8096"
  api_key: "8fa1a15a2a484d6fb86167cd31b3cef2"
  user_id: 'b128da17dbf5412bac37c096e25f2de5'
  item_id: 'ab532873de6a4fcd09ca15f5d59cd55a'
  playlists_id: '953141ca3d64b4e0bf3ff52b29bcbbab'

web_scraper:
  proxy:
    enable: True
    host: 127.0.0.1
    port: 7890
    secret: eb1dd2b3-975d-423f-81c9-3ee7e0551c31

download_client:
  type: "qBittorrent"
  port: 8080
  password: "adminadmin"
  download_folder: "D:/Downloads/dev"

app:
  environment: development