# app-prod.yml - 生产环境特定配置
database:
  password: "prod_strong_password"
  dbname: movie_prod

redis:
  password: "prod_redis_pass"

jellyfin:
  api_url: "http://prod.jellyfin.com:8096"
  api_key: "prod_key"
  user_id: 'prod_user'
  item_id: 'prod_item'

download_client:
  type: "qBittorrent"
  password: "prod_qb_pass"
  download_folder: "/data/downloads/prod"

app:
  environment: production