# app-dev.yml - 开发环境配置
# 开发环境使用直接配置，生产环境使用环境变量
database:
  password: "123456"
  dbname: movie

jellyfin:
  api_url: "http://127.0.0.1:8096"
  api_key: "1d4f983cf0a04522a444965fdfbfde9e" #密钥
  user_id: '5207a4b5a7bf4167ae81ba9d5f341c74' #root用户ID
  item_id: '3227ce1e069754c594af25ea66d69fc7' #电影库Id
  playlists_id: 'c89aa4ba14db3d46f85eef3ad0f8a569'  # 播放列表ID,未更新


download_client:
  type: "qBittorrent"
  port: 6363
  password: "adminadmin"
  download_folder: ""

chart:
  chart_list_path: "data/chart_list/"
  markdown_reader: normal # normal or top_250
  chart_type:
    name: javbus # javdb_top2502 or javbus
    description: 'come from javbus' # come from javbus

app:
  environment: development