# app-dev.yml - 开发环境特定配置
database:
  password: "dev123456"
  dbname: movie_dev

jellyfin:
  api_key: "dev_key"
  user_id: 'dev_user'
  item_id: 'dev_item'

web_scraper:
  proxy:
    enable: True
    host: 127.0.0.1
    port: 7890
    secret: eb1dd2b3-975d-423f-81c9-3ee7e0551c31

download_client:
  type: "qBittorrent"
  port: 8080
  password: "adminadmin"
  download_folder: "D:/Downloads/dev"

app:
  environment: development