# app-base.yml - 基础应用配置
# 配置策略：开发环境使用YAML配置，生产环境使用环境变量
database:
  host: "localhost"
  port: 3306
  user: root
  # password: 移至环境变量 DB_PASSWORD
  echo: true
  pool_size: 10
  echo_pool: true
  max_overflow: 20

redis:
  host: localhost
  port: 6379
  db: 0
  # password: 移至环境变量 REDIS_PASSWORD
  cache_timeout_seconds: 300

jellyfin:
  api_url: "http://127.0.0.1:8096"
  # api_key: 移至环境变量 JELLYFIN_API_KEY
  # user_id: 移至环境变量 JELLYFIN_USER_ID  
  # item_id: 移至环境变量 JELLYFIN_ITEM_ID
  # playlists_id: 移至环境变量 JELLYFIN_PLAYLISTS_ID
  client_type: jellyfinapi # jellyfinapi or jellyfin-apiclient-python

everything:
  exe_path: C:/Program Files/Everything/Everything.exe
  search_timeout_seconds: 5
  search_path: "D:/Movies"
  file_extensions: [mp4, mkv, avi]

web_scraper:
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
  timeout_seconds: 120
  retry_attempts: 10
  from: javdb # javdb or javbus or
  javdb:
    domain: "https://javdb.com"
    actor_search_uri: /search?q=%s&f=actor
    actor_detail_uri: '%s'
    cookie: ''
    movie_filters:
      min_evaluations: 500  # 最低评价人数
      min_score: 4.5  # 最低评分
      consecutive_failures: 5  # 连续不符合条件的电影数量，超过此值则终止
    actor_sort_type: 4  # 演员页面的排序方式：1-评分，2-热度，3-想看人数，4-看过人数
  javbus:
    domain: "https://www.javbus.com"
    actor_search_uri: /search?q=%s&f=actor
    actor_detail_uri: '%s'  # 直接使用演员URI，不需要额外参数
    cookie: ''
  proxy:
    enable: True
    # 代理类型优先级（按顺序尝试）
    priority: 
      - "clash_verge"      # 优先使用Clash.Verge
      - "clash_for_windows" # 其次Clash for Windows
    
    # 默认代理配置（如果自动检测失败）
    fallback:
      enable: true
      host: "127.0.0.1"
      port: 7890
      api_port: 9097
      # secret: 移至环境变量 PROXY_SECRET
      selector: "Proxy"
      
    # 特定软件配置覆盖（可选）
    clash_verge:
      config_path: "auto"  # auto表示自动检测，或手动指定路径
      # 手动路径示例: "C:/Users/{user}/AppData/Roaming/io.github.clash-verge-rev.clash-verge-rev/config.yaml"
      
    clash_for_windows:
      config_path: "auto"
      # 手动路径示例: "C:/Users/{user}/AppData/Roaming/Clash for Windows/config.yaml"



download_client:
  type: "qBittorrent"
  host: "127.0.0.1"
  port: 6363
  username: "admin"
  # password: 移至环境变量 QB_PASSWORD
  max_retry_attempts: 10

chart:
  chart_list_path: "data/chart_list/"
  markdown_reader: normal # normal or top_250
  chart_type:
    name: javbus # javdb_top2502 or javbus
    description: 'come from javbus' # come from javbus
  chart_content:
    entity_type: actor # movie or actor
    actor_min_evaluations: 200  # 演员电影的最低评价人数
    actor_sort_type: 4  # 演员页面的排序方式：1-评分，2-热度，3-想看人数，4-看过人数




app:
  name: MovieListDownloader
  movie_list_file: "./data/chart_list/"