# app-test.yml - 测试环境特定配置
database:
  password: "123456"
  dbname: movie2

jellyfin:
  api_url: "http://192.168.31.45:8096"
  api_key: "8fa1a15a2a484d6fb86167cd31b3cef2"
  user_id: 'b128da17dbf5412bac37c096e25f2de5'
  item_id: 'ab532873de6a4fcd09ca15f5d59cd55a'
  playlists_id: '953141ca3d64b4e0bf3ff52b29bcbbab'
  retry_count: 20
  client_type: jellyfinapi # jellyfinapi or jellyfin-apiclient-python

chart:
  markdown_reader: normal # normal or top_250
  chart_type:
    name: "Z师傅" # javdb_top2502 or javbus
    description: 'come from javbus' # come from javbus
  chart_content:
    entity_type: actor # movie or actor


web_scraper:
  from: javdb # javdb or javbus or
  javdb:
    domain: "https://javdb.com"
    actor_search_uri: /search?q=%s&f=actor
    actor_detail_uri: '%s'  # 直接使用演员URI，不需要额外参数
    cookie: ''
  javbus:
    domain: "https://www.javbus.com"
    actor_search_uri: /search?q=%s&f=actor
    actor_detail_uri: '%s'  # 直接使用演员URI，不需要额外参数
    cookie: ''

download_client:
  host: "192.168.31.45"
  port: 6363
  type: "qBittorrent"
  password: "adminadmin"
  download_folder: ""
  add_torrent_max_retries: 100

app:
  environment: testing