# app-base.yml - 基础应用配置
database:
  host: "localhost"
  port: 3306
  user: root
  echo: true
  pool_size: 10
  echo_pool: true
  max_overflow: 20

redis:
  host: localhost
  port: 6379
  db: 0
  cache_timeout_seconds: 300

jellyfin:
  api_url: "http://127.0.0.1:8096"
  client_type: jellyfinapi # jellyfinapi or jellyfin-apiclient-python

everything:
  exe_path: C:/Program Files/Everything/Everything.exe
  search_timeout_seconds: 5
  search_path: "D:/Movies"
  file_extensions: [mp4, mkv, avi]

web_scraper:
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
  timeout_seconds: 120
  retry_attempts: 10
  from: javdb # javdb or javbus or
  javdb:
    domain: "https://javdb.com"
    actor_search_uri: /search?q=%s&f=actor
    actor_detail_uri: '%s'
    cookie: ''
    movie_filters:
      min_evaluations: 200  # 最低评价人数
      min_score: 3.5  # 最低评分
      consecutive_failures: 5  # 连续不符合条件的电影数量，超过此值则终止
    actor_sort_type: 4  # 演员页面的排序方式：1-评分，2-热度，3-想看人数，4-看过人数
  javbus:
    domain: "https://www.javbus.com"
    actor_search_uri: /search?q=%s&f=actor
    actor_detail_uri: '%s'  # 直接使用演员URI，不需要额外参数
    cookie: ''
  proxy:
    enable: True
    host: 127.0.0.1
    port: 7890
    api_port: 60963
    secret: eb1dd2b3-975d-423f-81c9-3ee7e0551c31
    selector: Proxy # 策略组？


download_client:
  type: "qBittorrent"
  host: "127.0.0.1"
  port: 6363
  username: "admin"
  max_retry_attempts: 10

chart:
  chart_list_path: "data/chart_list/"
  markdown_reader: normal # normal or top_250
  chart_type:
    name: javbus # javdb_top2502 or javbus
    description: 'come from javbus' # come from javbus
  chart_content:
    entity_type: actor # movie or actor
    actor_min_evaluations: 200  # 演员电影的最低评价人数
    actor_sort_type: 4  # 演员页面的排序方式：1-评分，2-热度，3-想看人数，4-看过人数




app:
  name: MovieListDownloader
  movie_list_file: "./data/chart_list/"