# app-test.yml - 测试环境特定配置
database:
  password: "test123456"
  dbname: movie_test

jellyfin:
  api_key: "test_key"
  user_id: 'test_user'
  item_id: 'test_item'

qbittorrent:
  password: "testadmin"
  download_folder: "D:/Downloads/test"

app:
  environment: testing