# app-dev.yml - 开发环境特定配置
database:
  password: "dev123456"
  dbname: movie_dev

jellyfin:
  api_key: "dev_key"
  user_id: 'dev_user'
  item_id: 'dev_item'

web_scraper:
  proxy_enable: true
  proxy_url: "http://127.0.0.1:7890"

download_client:
  type: "qBittorrent"
  port: 8080
  password: "adminadmin"
  download_folder: "D:/Downloads/dev"

app:
  environment: development