# app-test.yml - 测试环境特定配置
database:
  password: "123456"
  dbname: movie2

jellyfin:
  api_url: "http://192.168.31.45:8096"
  api_key: "8fa1a15a2a484d6fb86167cd31b3cef2"
  user_id: 'b128da17dbf5412bac37c096e25f2de5'
  item_id: 'ab532873de6a4fcd09ca15f5d59cd55a'
  playlists_id: '953141ca3d64b4e0bf3ff52b29bcbbab'
  retry_count: 20
  client_type: jellyfinapi # jellyfinapi or jellyfin-apiclient-python

chart:
  markdown_reader: normal # normal or top_250
  chart_type:
    name: "Z师傅" # javdb_top2502 or javbus
    description: 'come from javbus' # come from javbus
  chart_content:
    entity_type: actor # movie or actor
    actor_min_evaluations: 200  # 演员电影的最低评价人数
    actor_sort_type: 4  # 演员页面的排序方式：1-评分，2-热度，3-想看人数，4-看过人数

web_scraper:
  cookie: ''

download_client:
  host: "192.168.31.45"
  port: 6363
  type: "qBittorrent"
  password: "adminadmin"
  download_folder: ""
  add_torrent_max_retries: 100

app:
  environment: testing