# app-test.yml - 测试环境特定配置
database:
  password: "123456"
  dbname: movie

jellyfin:
  api_url: "http://192.168.31.45:8096"
  api_key: "8fa1a15a2a484d6fb86167cd31b3cef2"
  user_id: 'b128da17dbf5412bac37c096e25f2de5'
  item_id: 'ab532873de6a4fcd09ca15f5d59cd55a'
  playlists_id: '953141ca3d64b4e0bf3ff52b29bcbbab'
  client_type: jellyfinapi # jellyfinapi or jellyfin-apiclient-python

chart:
  markdown_reader: top_250 # normal or top_250
  chart_type:
    name: javdb_top2502 # javdb_top2502 or javbus
    description: 'come from javdb' # come from javbus

download_client:
  host: "192.168.31.45"
  port: 6363
  type: "qBittorrent"
  password: "adminadmin"
  download_folder: ""
  retry_count: 20

app:
  environment: testing