# logging-dev.yml - 开发环境日志配置
handlers:
  console:
    level: DEBUG
  file:
    level: DEBUG
    filename: app.log
  error_file:
    level: DEBUG
    filename: error.log

loggers:
  root:
    level: DEBUG
  sqlalchemy:
    level: DEBUG