# logging-base.yml - 基础日志配置
version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s - %(module)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  detailed:
    format: "%(asctime)s - %(name)s - %(module)s - %(funcName)s - %(lineno)d - %(levelname)s : %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: simple
    when: midnight
    interval: 1
    encoding: utf-8
  error_file:
    class: logging.handlers.RotatingFileHandler
    formatter: detailed
    maxBytes: 10485760
    encoding: utf-8

loggers:
  root:
    handlers: [console, file, error_file]
    propagate: true
  sqlalchemy:
    handlers: [file]
    propagate: false