# logging-prod.yml
log_directory: /var/log/myapp

handlers:
  console:
    level: WARNING
  file:
    level: INFO
    filename: app.log
    backupCount: 90
    mode: '0640'
  error_file:
    level: ERROR
    filename: error.log
    backupCount: 90
    mode: '0640'
  database:
    level: WARNING
    filename: sql.log
    backupCount: 30
    mode: '0640'

loggers:
  root:
    level: INFO
    handlers: [file, error_file]
  sqlalchemy:
    level: WARNING
    propagate: False

database_log:
  console_output: WARNING