# logging-prod.yml - 生产环境日志配置
log_directory: /var/log/myapp

handlers:
  console:
    level: WARNING
  file:
    level: INFO
    filename: prod-app.log
    backupCount: 90
  error_file:
    level: ERROR
    filename: prod-error.log
    backupCount: 90

loggers:
  root:
    level: INFO
  sqlalchemy:
    level: WARNING