# logging-default.yml - 默认配置，包含所有基础设置
log_directory: logs

version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s - %(module)s - %(thread)d - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  detailed:
    format: "%(asctime)s - %(name)s - %(module)s - %(funcName)s - %(lineno)d - %(thread)d - %(threadName)s - %(process)d - %(levelname)s : %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  database:
    format: "%(asctime)s - %(levelname)s - [%(name)s] - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: simple
    filename: app.log
    when: midnight
    interval: 1
    backupCount: 30
    encoding: utf-8
  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: error.log
    maxBytes: 10485760  # 10MB
    backupCount: 30
    encoding: utf-8
  database:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: database
    filename: sql.log
    maxBytes: 10485760
    backupCount: 5
    encoding: utf-8

loggers:
  root:
    level: INFO
    handlers: [console, file, error_file]
  sqlalchemy:
    level: INFO
    handlers: [database]
    propagate: False

database_log:
  console_output: INFO
