# Loggers
version: 1
loggers:
  root:
    level: DEBUG
    handlers: [console]
  file:
    level: DEBUG
    handlers: [file]
    propagate: True
  fileAndConsole:
    level: DEBUG
    handlers: [file, console]
    propagate: False

# Handlers
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: ./app.log
    when: midnight
    interval: 1
    backupCount: 30
    encoding: utf-8

# Formatters
formatters:
  simple:
    format: "%(asctime)s - %(module)s - %(thread)d - %(levelname)s : %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
