# logging-dev.yml
log_directory: logs

handlers:
  console:
    level: DEBUG
    formatter: detailed
  file:
    level: DEBUG
    filename: app.log
    backupCount: 30
  error_file:
    level: ERROR
    filename: error.log
    backupCount: 30
  database:
    level: DEBUG
    filename: sql.log
    backupCount: 5

loggers:
  root:
    level: DEBUG
  sqlalchemy:
    level: DEBUG
    propagate: True

database_log:
  console_output: DEBUG