# logging-prod.yml - 生产环境日志配置
handlers:
  console:
    level: WARNING
  file:
    level: INFO
    filename: app.log
    backupCount: 90
  error_file:
    level: ERROR
    filename: error.log
    backupCount: 90

loggers:
  root:
    level: INFO
  sqlalchemy:
    level: WARNING