# logging-test.yml - 测试环境日志配置
handlers:
  console:
    level: DEBUG
  file:
    level: DEBUG
    filename: app.log
    backupCount: 5
  error_file:
    level: DEBUG
    filename: error.log
    backupCount: 5

loggers:
  root:
    level: DEBUG
  sqlalchemy:
    level: DEBUG