# logging-test.yml - 测试环境日志配置
log_directory: logs/test

handlers:
  console:
    level: DEBUG
  file:
    level: DEBUG
    filename: test-app.log
    backupCount: 5
  error_file:
    level: DEBUG
    filename: test-error.log
    backupCount: 5

loggers:
  root:
    level: DEBUG
  sqlalchemy:
    level: DEBUG