version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s - %(module)s - %(thread)d - %(levelname)s : %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  database:
    format: "%(asctime)s - %(levelname)s - [%(name)s] - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: ./logs/app.log
    when: midnight
    interval: 1
    backupCount: 30
    encoding: utf-8
  database:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: database
    filename: ./logs/sql.log
    maxBytes: 10485760  # 10MB
    backupCount: 5

loggers:
  root:
    level: DEBUG
    handlers: [console, file, database]
  sqlalchemy:
    level: INFO
    handlers: [database]
    propagate: False

database_log:
  console_output: DEBUG